export const elements = {
  todoInput: document.getElementById("todo-input"),
  addBtn: document.getElementById("add-btn"),
  groupNameInput: document.getElementById("group-name"),
  addGroupBtn: document.getElementById("add-group-btn"),
  groupSelector: document.getElementById("group-selector"),
  groupsContainer: document.getElementById("groups-container"),
  filterBtns: document.querySelectorAll(".filter-btn"),
  clearCompletedBtn: document.getElementById("clear-completed"),
  clearAllBtn: document.getElementById("clear-all"),
  clearAllGroupsBtn: document.getElementById("clear-all-groups"),
  itemsLeftSpan: document.getElementById("items-left"),
  itemsCompletedSpan: document.getElementById("items-completed"),
  filterInCurrentGroup: document.getElementById("filter-in-current-group"),
  noGroupsMessage: document.getElementById("no-groups-message"),
  clearCacheBtn: document.getElementById("clear-cache-btn"),
  importWordBtn: document.getElementById("import-word-btn"),
  wordFileInput: document.getElementById("word-file-input"),
};
